[theme]

# Primary accent for interactive elements
primaryColor = '#5681d0'

# Background color for the main content area
backgroundColor = '#975c8d'


# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = "#708b6c"


# Color used for almost all text: https://hexcolorpedia.com/color/?q=blue
textColor="darkblue"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"